decision_maker_per_plc:
- actuators:
  - decision_maker: rule
    name: PU1
  name: PLC1
- actuators:
  - decision_maker: scada
    name: PU5
  name: PLC3
demand: pdd
inp_file: ctown_map.inp
iterations: 400
log_level: debug
mode: hybridcontrol
network_topology_type: complex
output_path: CtownTestAttack
plcs:
- actuators:
  - PU1
  - PU2
  name: PLC1
  sensors:
  - PU1F
  - PU2F
  - J280
  - J269
- name: PLC2
  sensors:
  - T1
- actuators:
  - V2
  - PU4
  - PU5
  - PU6
  - PU7
  name: PLC3
  sensors:
  - T2
  - V2F
  - J300
  - J256
  - J289
  - J415
  - J14
  - J422
  - PU4F
  - PU5F
  - PU6F
  - PU7F
- name: PLC4
  sensors:
  - T3
- actuators:
  - PU8
  - PU10
  - PU11
  name: PLC5
  sensors:
  - PU8F
  - PU10F
  - PU11F
  - J302
  - J306
  - J307
  - J317
- name: PLC6
  sensors:
  - T4
- name: PLC7
  sensors:
  - T5
- name: PLC8
  sensors:
  - T6
- name: PLC9
  sensors:
  - T7
simulator: epynet
