attacks:
  network_attacks:
  - concealment_data:
      capture_end: 15
      capture_start: 5
      replay_start: 20
      type: network_replay
    name: plc4attack
    tags:
    - offset: -4.0
      tag: T41
    target: PLC2
    trigger:
      end: 40
      start: 5
      type: time
    type: concealment_mitm
demand: pdd
demand_patterns: demands_MiniAnyTown.csv
inp_file: MiniAnyTown.inp
iterations: 50
log_level: debug
mode: plccontrol
network_topology_type: simple
output_path: PlcControl_ConcelMiTMRePlay_Simple
plcs:
- actuators:
  - P79
  name: PLC1
- name: PLC2
  sensors:
  - T41
- name: PLC3
  sensors:
  - T42
- actuators:
  - P1
  name: PLC4
simulator: epynet
