attacks:
  network_attacks:
  - name: T41MiM
    tags:
    - offset: -5.2
      scaleParam: -1.1
      scaleTime: 1
      tag: T41
    target: SCADA
    trigger:
      end: 30
      start: 2
      type: time
    type: seq_mitm
demand: pdd
demand_patterns: demands_MiniAnyTown.csv
inp_file: MiniAnyTown.inp
iterations: 300
log_level: debug
mode: hybridcontrol
network_topology_type: complex
output_path: MitmSeqPLC4
plcs:
- actuators:
  - P79
  name: PLC1
- name: PLC2
  sensors:
  - T41
- name: PLC3
  sensors:
  - T42
- actuators:
  - P1
  name: PLC4
- name: PLCJunc2
  sensors:
  - J2
  - J13
- name: PLCJunc21
  sensors:
  - J21
  - V1F
simulator: epynet
