attacks:
  network_attacks:
  - direction: source
    name: plc2AttackerUnit
    target: PLC2
    trigger:
      end: 300
      start: 175
      type: time
    type: simple_dos
demand: pdd
demand_patterns: demands_MiniAnyTown.csv
inp_file: MiniAnyTown.inp
iterations: 400
log_level: debug
mode: scadacontrol
network_topology_type: complex
output_path: Testing
plcs:
- actuators:
  - P79
  name: PLC1
- name: PLC2
  sensors:
  - T41
- name: PLC3
  sensors:
  - T42
- actuators:
  - P1
  name: PLC4
- name: JPLC1
  sensors:
  - J2
  - J13
- name: VPLC1
  sensors:
  - V1F
- name: VPLC2
  sensors:
  - V2F
