inp_file: EdenTownScada.inp
output_path: outputNew
iterations: 500
network_topology_type: complex
plcs: !include EdenTownScada_plc.yaml
demand: pdd
log_level: debug
demand_patterns: demands_EdenTownScada.csv
mode: scadacontrol
decision_maker_per_scadacommand: !include EdenTown_decision_scada.yaml
attacks: !include Plc3AndPlc2_Dos.yaml

