inp_file: MiniAnyTown.inp
output_path: ScadaControlDoS_Complex
iterations: 50
network_topology_type: complex
plcs: !include MiniAnyTown_plc.yaml

simulator: epynet
demand: pdd
log_level: debug
demand_patterns: demands_MiniAnyTown.csv
mode: scadacontrol 
#attacks: !include anytown_concealment_mitm.yaml
attacks: !include Plc4_Dos.yaml

