demand: pdd
demand_patterns: demands_MiniAnyTown.csv
inp_file: MiniAnyTown.inp
iterations: 300
log_level: debug
mode: plccontrol
network_topology_type: complex
output_path: DoS_PLC4_ScadaC
plcs:
- actuators:
  - P79
  name: PLC1
- actuators:
  - V1
  name: PLC2
  sensors:
  - T41
  - V1F
  - J21
- name: PLC3
  sensors:
  - T42
- actuators:
  - P1
  name: PLC4
  sensors:
  - J2
  - P1F
simulator: epynet
