attacks:
  network_attacks:
  - concealment_data:
      capture_end: 58
      capture_start: 54
      replay_start: 100
      type: network_replay
    name: plc4attack
    tags:
    - offset: -4.0
      tag: T41
    target: PLC4
    trigger:
      end: 200
      start: 5
      type: time
    type: concealment_mitm
demand: pdd
demand_patterns: demands_MiniAnyTown.csv
inp_file: MiniAnyTown.inp
iterations: 300
log_level: debug
mode: scadacontrol
network_topology_type: complex
output_path: MitmConcealPLC4
plcs:
- actuators:
  - P79
  name: PLC1
- name: PLC2
  sensors:
  - T41
- name: PLC3
  sensors:
  - T42
- actuators:
  - P1
  name: PLC4
- name: JPLC1
  sensors:
  - J2
  - J13
- name: VPLC1
  sensors:
  - V1F
- name: VPLC2
  sensors:
  - V2F
simulator: epynet
