attacks:
  network_attacks:
  - name: T41MiM
    tags:
    - offset: -4.0
      tag: T41
    target: PLC4
    trigger:
      end: 200
      start: 100
      type: time
    type: mitm
demand: pdd
demand_patterns: demands_MiniAnyTown.csv
inp_file: MiniAnyTownBackUp.inp
iterations: 300
log_level: debug
mode: plccontrol
network_topology_type: complex
output_path: Testing
plcs:
- actuators:
  - P79
  name: PLC1
- name: PLC2
  sensors:
  - T41
- name: PLC3
  sensors:
  - T42
- actuators:
  - P1
  name: PLC4
- name: PLCJunc2
  sensors:
  - J2
  - J13
- name: PLCJunc21
  sensors:
  - J21
  - V1F
simulator: epynet
