inp_file: EdenTown.inp
output_path: DoS_PLC4_PLCC_Guard
iterations: 600
network_topology_type: complex
plcs: !include EdenTown_plc.yaml
demand: pdd
log_level: debug
demand_patterns: demands_EdenTown.csv
mode: plccontrol
decision_maker_per_plc: !include EdenTown_decision_plc.yaml
attacks: !include Plc4_Dos.yaml
